# Builds ACM firmware

name: acm

on:
  workflow_dispatch:
  push:
    paths:
    - 'components/aerodynamic-control-module/**'

jobs:
  acm-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose run acm