# Builds ACM firmware

name: ACM

on:
  push:
    paths:
    - 'components/acm/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose run acm