# Builds firmware for all components

name: all-components

on:
  push:
    paths:
    - 'components/**'

jobs:
  acm-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose run acm

  dam-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose run dam

  dlm-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose run dlm

  pdm-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose run pdm