# Builds DAM firmware

name: dam

on:
  workflow_dispatch:
  push:
    paths:
    - 'components/data-acquisition-module/**'

jobs:
  dam-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose run dam