# Builds DLM firmware

name: dlm

on:
  push:
    paths:
    - 'components/dlm/**'

jobs:
  dlm-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose run dlm