# Builds DLM firmware

name: dlm

on:
  workflow_dispatch:
  push:
    paths:
    - 'components/data-logging-module'

jobs:
  dlm-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Clean
      run: docker-compose run dlm-clean

    - name: Build
      run: docker-compose run dlm
