# Builds PDM firmware

name: PDM

on:
  push:
    paths:
    - 'components/pdm'

jobs:
  pdm-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose run pdm